### ISSUE TITLE
[FEAT] My First Issue & Pr 

### ISSUE THREAD

**Issue by mininim** [KinGSSajonjaltwo/PictureThat-IOS#1]
## 💡 issue
Issue & Pr 맛보기

## 📝 todo
- [x] issue 템플릿 추가
- [x] Pr 템플릿 추가
- [x] issue 만들기
- [x] merge Pull request

**Comment by mininim** [comment]
# 🎉

**Comment by mininim** [comment]
# 🎉

**Comment by mininim** [comment]
# 🎉
