### ISSUE TITLE
[FEAT] Firebase에서 card 데이터 가져오기

### ISSUE THREAD

**Issue by mininim** [KinGSSajonjaltwo/PictureThat-IOS#26]
## 💡 issue
Firebase(Realtime DB)에서 card 데이터 가져오기

## 📝 todo
- [x] Fdb에서 총 카드 장수 값 읽어오기 
- [ ] 무작위 인덱스값 추출 기능
- [ ] card 데이터 초기화하기

**Comment by mininim** [comment]
네트워킹 부분과 ViewModel 부분이 너모 어려워서 좀 더 작은 단위로 나눠서 다시 해결하고자함
돌 아 올 게 딱 기 다 려
