### ISSUE TITLE
[FEAT] CardViewModel getCards from Firebase

### ISSUE THREAD

**Issue by mininim** [KinGSSajonjaltwo/PictureThat-IOS#36]
## 💡 issue

CardViewModel getCards() 메소드 구현하기

## 📝 todo
- [x] firebase에서 cards 가져오기
- [x] self.cards에 저장하기
- [x] 비동기 처리(async await) &  호출부에서의 비동기 처리 확인

**Comment by mininim** [comment]
https://www.youtube.com/watch?v=p6q1RmYUsNU&list=PLwvDm4Vfkdphr2Dl4sY4rS9PLzPdyi8PM&index=1

**Comment by mininim** [comment]
https://ios-development.tistory.com/958

**Comment by mininim** [comment]
firebaseRealTimeDB 비동기 방식이기때문에
DispatchGroup 과 completionhandler를 사용해서  getCards() 메소드 구현!
